### ISSUE TITLE
THE ISSUE

### ISSUE THREAD

**Issue by rashtug** [Vikrammel/EasyTrage#26]
> nodemon@2.0.15 postinstall /usr/local/lib/node_modules/nodemon
server_1  | > node bin/postinstall || exit 0
server_1  | 
server_1  | Love nodemon? You can now support the project via the open collective:
server_1  |  > https://opencollective.com/nodemon/donate
server_1  | 
server_1  | npm WARN notsup Unsupported engine for update-notifier@5.1.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: update-notifier@5.1.0
server_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
server_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
server_1  | npm WARN notsup Unsupported engine for is-installed-globally@0.4.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: is-installed-globally@0.4.0
server_1  | npm WARN notsup Unsupported engine for boxen@5.1.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: boxen@5.1.2
server_1  | npm WARN notsup Unsupported engine for is-npm@5.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: is-npm@5.0.0
server_1  | npm WARN notsup Unsupported engine for chalk@4.1.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.2
server_1  | npm WARN notsup Unsupported engine for semver@7.3.5: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: semver@7.3.5
server_1  | npm WARN notsup Unsupported engine for camelcase@6.3.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: camelcase@6.3.0
server_1  | npm WARN notsup Unsupported engine for type-fest@0.20.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: type-fest@0.20.2
server_1  | npm WARN notsup Unsupported engine for wrap-ansi@7.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: wrap-ansi@7.0.0
server_1  | npm WARN notsup Unsupported engine for global-dirs@3.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: global-dirs@3.0.0
server_1  | npm WARN notsup Unsupported engine for ini@2.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: ini@2.0.0
server_1  | npm WARN notsup Unsupported engine for lru-cache@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
server_1  | npm WARN notsup Not compatible with your version of node/npm: lru-cache@6.0.0
server_1  | 
server_1  | + nodemon@2.0.15
server_1  | updated 1 package in 1.955s
server_1  | /usr/local/lib/node_modules/nodemon/node_modules/update-notifier/index.js:58
server_1  | 			} catch {
server_1  | 			        ^
server_1  | 
server_1  | SyntaxError: Unexpected token {
server_1  |     at createScript (vm.js:80:10)
server_1  |     at Object.runInThisContext (vm.js:139:10)
server_1  |     at Module._compile (module.js:617:28)
server_1  |     at Object.Module._extensions..js (module.js:664:10)
server_1  |     at Module.load (module.js:566:32)
server_1  |     at tryModuleLoad (module.js:506:12)
server_1  |     at Function.Module._load (module.js:498:3)
server_1  |     at Module.require (module.js:597:17)
server_1  |     at require (internal/module.js:11:18)
server_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/bin/nodemon.js:15:3)
easytrage_server exited with code 1

**Comment by FarrukhKamalov** [comment]
pm2 install
